### ISSUE TITLE
ToCss Function Modifies File Paths Unexpectedly, Causing Issues with Content Loading in Blazor

### ISSUE THREAD

**Issue by cbcrouse** [hassanhabib/SharpStyles#12]
## Summary

`ToCss` modifies the file path to be lowercase and separate words with dashes. This feature is not opt-in and also not opt-out. This is a problem for Blazor because of how content is loaded in the `_content/{AssemblyName}` path when using Razor projects.

### Example setup

```csharp
private void SetupStyle()
{
    // An example path would be in the wwwroot as:
    // /_content/MyCompanyName.MyAppName.MyProjectName/images/hero.png
    // In production, this path would be defined in a constant for optimal reuse
    var path = $"_content/{typeof(App).Assembly.GetName().Name}/images/hero.png";
    
    Style = new PublicProfileStyle
    {
        BannerContainer = new SharpStyle
        {
            // Set the path of the background image using interpolation to avoid having hard-coded paths in css
            Background = $"linear-gradient(to top, #000 0%, rgba(0,0,0,0) 100%),url('{path}')"
        }
    };
}

```

### Actual Output

```css
.banner-container {
	background: linear-gradient(to top, #000 0%, rgba(0,0,0,0) 100%),url('/_content/my-company-name.my-app-name.my-project-name/images/hero.png');
}
```

### Expected Output

```css
.banner-container {
	background: linear-gradient(to top, #000 0%, rgba(0,0,0,0) 100%),url('/_content/MyCompanyName.MyAppName.MyProjectName/images/hero.png');
}
```
