### ISSUE TITLE
FEATURE: Support Webkit CSS Properties 

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/SharpStyles#7]
## The Ask
If we want to customize some web behaviour, we need to write CSS properties as follows:

```css
  .e-rating {
        -webkit-text-stroke: 2px #ae9e9d;        
    }
```
Make sure this is possible using SharpStyles
